#!/bin/sh
set -e

/usr/bin/docker pull kontena/server:0.5
/usr/bin/docker pull kontena/haproxy:latest
/usr/bin/docker pull mongo:2.8
/usr/bin/docker pull redis:2.8

/usr/bin/docker inspect kontena-server-mongo-data > /dev/null || \
  /usr/bin/docker create --name kontena-server-mongo-data mongo:2.8
/usr/bin/docker inspect kontena-server-redis-data  > /dev/null || \
  /usr/bin/docker create --name kontena-server-redis-data redis:2.8

start kontena-server-mongo || true
start kontena-server-redis || true
start kontena-server-api || true
