#!/bin/sh
set -e

. /etc/default/kontena-agent
. /etc/default/kontena-weave

PEER_IP=$(ifconfig ${WEAVE_PEER_INTERFACE} 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
if [ -z $PEER_IP ]; then
  # fallback to eth0
  PEER_IP=$(ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
fi
URI=$(echo ${KONTENA_URI} | sed s/ws/http/)
GRID_URI="${URI}/v1/nodes"
NODE_ID=$(cat /etc/docker/key.json | jq -r '.kid')
PAYLOAD="{\"id\": \"${NODE_ID}\",\"private_ip\": \"${PEER_IP}\"}"
NODE_INFO=$(curl -XPOST -k -H "Kontena-Grid-Token: ${KONTENA_TOKEN}" -d "${PAYLOAD}" -Ls ${GRID_URI})
NODE_NUMBER=$(echo ${NODE_INFO} | jq -r '.node_number')

sed -i -r "s#WEAVE_BRIDGE=.*#WEAVE_BRIDGE=\"10.81.0.${NODE_NUMBER}/16\"#" /etc/default/kontena-weave
sed -i -r "s#\#DOCKER_OPTS=.*#DOCKER_OPTS=\"--bridge=weave --fixed-cidr='10.81.${NODE_NUMBER}.0/24' --insecure-registry='10.81.0.0/16'\"#" /etc/default/docker

/usr/local/bin/weave setup
/sbin/start kontena-weave || true
/sbin/start kontena-weave-helper || true
