#!/usr/bin/env ruby
# encoding: UTF-8

# resolve bin path, ignoring symlinks
require 'pathname'
bin_file = Pathname.new(__FILE__).realpath
$:.unshift File.expand_path('../../..', bin_file)

require 'kontena/scripts/completer'
