#!/usr/bin/env bash

# This file exists mostly for backwards dependency to
# allow the old "which kontena && . foofoo/init"
# completion loading
_kontena_complete() {
  COMPREPLY=()
  local word="${COMP_WORDS[COMP_CWORD]}"
  local completions="$(kontena complete ${COMP_WORDS[*]})"
  COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

if [ "$ZSH_VERSION" != "" ]; then
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit
fi

which kontena > /dev/null && complete -F _kontena_complete kontena
