json.domain authorization.domain
json.challenge authorization.challenge
json.challenge_opts authorization.challenge_opts
json.authorization_type authorization.authorization_type
json.linked_service authorization.grid_service.to_path if authorization.grid_service
json.service_deploy_id authorization.service_deploy_id if authorization.service_deploy_id
