json.domain authorization.domain
json.challenge authorization.challenge
json.authorization_type authorization.authorization_type
json.challenge_opts authorization.challenge_opts
json.linked_service authorization.grid_service.to_path if authorization.grid_service