source 'https://rubygems.org'

gem 'kontena_client', github: 'kontena/kontena-client-ruby'

# Specify your gem's dependencies in kontena-cli.gemspec
gemspec
group :development, :test do
  gem "rspec"
end
