source 'https://rubygems.org'

gem 'kontena-websocket-client', git: 'https://github.com/kontena/kontena-websocket-client.git'

# Specify your gem's dependencies in kontena-cli.gemspec
gemspec

group :development, :test do
  gem "rspec"
  gem 'simplecov', :require => false, :group => :test
  gem "kontena-plugin-hello", path: "./examples/kontena-plugin-hello"
  gem 'pry', require: false
  gem 'pry-byebug', require: false
  gem 'webmock', require: false
end
