#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Fetch etcd discovery url from Kontena Master
db_get kontena-agent/server_uri
URI="${RET}"
URI=$(echo ${URI} | sed s/ws/http/)

db_get kontena-agent/grid_token
TOKEN="${RET}"

GRID_URI="${URI}/v1/nodes"
NODE_ID=$(cat /etc/docker/key.json | jq -r '.kid')
ETCD_DISCOVERY=$(curl -XPOST -H "Kontena-Grid-Token: ${TOKEN}" -d "{\"id\": \"${NODE_ID}\"}" -Ls ${GRID_URI} | jq -r '.grid.discovery_url')
ETCD_DISCOVERY="ETCD_DISCOVERY=${ETCD_DISCOVERY}"

sed -i -r "s#\#ETCD_DISCOVERY=.*#${ETCD_DISCOVERY}#" /etc/default/kontena-etcd

start kontena-etcd || exit 0
