FROM gliderlabs/alpine:3.2
MAINTAINER jari@kontena.io

RUN apk update && apk --update add ruby ruby-dev ca-certificates libssl1.0 openssl libstdc++

ADD Gemfile /app/
ADD Gemfile.lock /app/

RUN apk --update add --virtual build-dependencies build-base openssl-dev && \
    gem install bundler && \
    cd /app ; bundle install --without development test && \
    apk del build-dependencies

ENV CADVISOR_URL http://cadvisor:8080/api/v1.2/docker/

WORKDIR /app
ADD . /app

CMD ["/app/bin/kontena-agent"]
