source 'https://rubygems.org'

gem 'docker-api'
gem 'faye-websocket'
gem 'msgpack'
gem 'activesupport', '~> 4.2.0'
gem 'celluloid', '~> 0.16.0'
gem 'etcd'

group :development, :test do
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'dotenv', require: false
  gem 'webmock', require: false
end
