source 'https://rubygems.org'

gem 'docker-api'
gem 'eventmachine', '~> 1.0.8'
gem 'faye-websocket', '~> 0.10.1'
gem 'msgpack'
gem 'activesupport', '~> 4.2.0'
gem 'celluloid', '~> 0.17.3'
gem 'etcd'
gem 'statsd-ruby'
gem 'vmstat'

group :development, :test do
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'dotenv', require: false
  gem 'webmock', require: false
  gem 'simplecov', require: false
end
